# Generated by Django 3.2 on 2022-12-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='used_stock',
            field=models.IntegerField(default=0),
        ),
    ]
