# Generated by Django 3.2 on 2022-12-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delights', '0004_auto_20221209_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='handwork_price',
            field=models.FloatField(default=0.0),
        ),
    ]
